<?php
return [
'star5' => [
"http://feeds.feedburner.com/TheGeekStuff",
"http://www.alistapart.com/rss.xml",
"http://www.seotest.cn/rss.xml",
],
'star1' => [
"http://feeds.feedburner.com/TheGeekStuff",
"http://www.alistapart.com/rss.xml",
"http://www.stevesouders.com/blog/feed/",
"http://feeds.feedburner.com/nettuts",
"http://feeds.feedburner.com/ajaxian",
"http://feeds.feedburner.com/mr6",
"http://www.jaceju.net/blog/?feed=rss2",
"http://feed.read.org.cn/",
"http://blog.codingnow.com/atom.xml",
"http://lifesinger.org/blog/?feed=rss2",
"http://feed.feedsky.com/chedong",
"http://feed.feedsky.com/roclinux",
"http://feed.ooso.net/",
"http://wangcong.org/blog/?feed=rss2",
"http://www.dbanotes.net/atom.xml",
"http://blog.csdn.net/lanphaday/Rss.aspx",
"http://feeds.feedburner.com/AjaxRain",
"http://www.real-blog.com/feed/",
"http://aqee.feedsportal.com/c/34519/f/631690/index.rss",
"http://www.mysqlab.net/blog/feed/",
"http://blog.csdn.net/heiyeshuwu/Rss.aspx",
"http://feeds.feedburner.com/cwr",
"http://feed.feedsky.com/bingo929",
"http://feeds.feedburner.com/dancewithnet",
"http://feed.css9.net/",
"http://iregex.org/feed",
"http://feeds.feedburner.com/TaobaoUiTeam",
"http://www.seotest.cn/rss.xml",
"http://cuikai-wh.com/feed",
"http://www.sinosplice.com/life/feed",
"http://andymao.com/andy/rss.xml",
"http://rss1.smashingmagazine.com/feed",
"http://blog.sina.com.cn/rss/1742316130.xml",
"http://feed.write.org.cn/",
"http://xinhuasheng1085.blog.hexun.com/rss2.aspx",
"http://ziyu100.blog.com/feed/",
"http://mindhacks.cn/feed",
"http://firecacada.blog.163.com/rss",
"http://www.perfgeeks.com/?feed=rss2",
"http://forfuture1978.javaeye.com/rss",
"http://blog.cnfol.com/zhanghongliang/Rss.xml",
"http://www.cnblogs.com/rss.aspx?teamid=118",
],
];


